development:
  adapter: postgresql
  encoding: utf8
  database: ajaxdemo-db-test_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: ajaxdemo-db-test_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: ajaxdemo-db-test_production
  pool: 5
  username:
  password: